matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
      yarn build:electron
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

before_deploy:
- if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x $HOME/scripts/travis-add-osx-cert.sh; fi
- if [ "$TRAVIS_OS_NAME" = osx ]; then $HOME/scripts/travis-add-osx-cert.sh; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
